name = "server-sg" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "sg.stbinternet.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.sg.stbinternet.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.sg.stbinternet.us.kg"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.sg.stbinternet.us.kg"
custom_domain = true

[[routes]]
pattern = "df.game.naver.com.sg.stbinternet.us.kg"
custom_domain = true

[[routes]]
pattern = "quiz.vidio.com.sg.stbinternet.us.kg"
custom_domain = true

[[routes]]
pattern = "quiz.int.vidio.com.sg.stbinternet.us.kg"
custom_domain = true

[[routes]]
pattern = "graph.instagram.com.sg.stbinternet.us.kg"
custom_domain = true

[[routes]]
pattern = "investors.spotify.com.sg.stbinternet.us.kg"
custom_domain = true

[[routes]]
pattern = "cache.netflix.com.sg.stbinternet.us.kg"
custom_domain = true

[[routes]]
pattern = "creativeservices.netflix.com.sg.stbinternet.us.kg"
custom_domain = true

[[routes]]
pattern = "support.zoom.us.sg.stbinternet.us.kg"
custom_domain = true

[[routes]]
pattern = "zaintest.vuclip.com.sg.stbinternet.us.kg"
custom_domain = true

[[routes]]
pattern = "live.iflix.com.sg.stbinternet.us.kg"
custom_domain = true

[[routes]]
pattern = "io.ruangguru.com.sg.stbinternet.us.kg"
custom_domain = true

[[routes]]
pattern = "gw.ruangguru.com.sg.stbinternet.us.kg"
custom_domain = true

[[routes]]
pattern = "data.mt.sg.stbinternet.us.kg"
custom_domain = true

[[routes]]
pattern = "www.udemy.com.sg.stbinternet.us.kg"
custom_domain = true

[[routes]]
pattern = "beta.zoom.us.sg.stbinternet.us.kg"
custom_domain = true


[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "e1550644-714b-444e-9702-d6cf02800c4f"
